using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TAICodeComplete
{
    public partial class TestForm1 : Form
    {
        public TestForm1()
        {
            InitializeComponent();
        }
        private void btnEnableAll_Click(object sender, EventArgs e)
        {
            this.txtID.Enabled = true;
            this.txtMessagingRefresh.Enabled = true;
            this.txtAutoLogOutTime.Enabled = true;
            this.txtCrisisInterventionRefresh.Enabled = true;
            this.txtCountyMAIDNumber.Enabled = true;
            this.txtCountyCode.Enabled = true;
            this.txtCountyAlphaCode.Enabled = true;
            this.txtLocationCode.Enabled = true;
            this.txtCountyName.Enabled = true;
            this.txtMemberRegistrationRefresh.Enabled = true;
            this.txtPeopleSoftVoucherNumber.Enabled = true;
            this.txtBESNUMBERTEST.Enabled = true;
            this.txtBESNUMBERLIVE.Enabled = true;
            this.txtMPINUMBERTEST.Enabled = true;
            this.txtMPINUMBERLIVE.Enabled = true;
            this.txtCOUNTYMCOCODEN.Enabled = true;
            this.txtCOUNTYMCOCODEA.Enabled = true;
            this.txtDPWNAME.Enabled = true;
            this.txtCONTACTNAME.Enabled = true;
            this.txtCONTACTPHONE.Enabled = true;
            this.txtCONTACTFAX.Enabled = true;
            this.txtCONTACTEMAIL.Enabled = true;
            this.txtLASTCONTROLNUM.Enabled = true;
            this.txtSubSystemNumber.Enabled = true;
            this.txtPFVoucherNumber.Enabled = true;
            this.txtPlanProviderID.Enabled = true;
            this.txtMPI_ICM.Enabled = true;
            this.txtMPI_TSM.Enabled = true;
            this.txtMPI_CI.Enabled = true;
            this.txtMPI_EI.Enabled = true;
            this.txtMPI_RC.Enabled = true;
            this.txtNPI_ICM.Enabled = true;
            this.txtNPI_TSM.Enabled = true;
            this.txtNPI_CI.Enabled = true;
            this.txtNPI_RC.Enabled = true;
            this.txtNPI_EI.Enabled = true;
            this.txtscanneddocsfolder.Enabled = true;
            this.txtEIN.Enabled = true;
            this.txtQueryTimeout.Enabled = true;
            this.dtpLastClaimDtlCreatedDate.Enabled = true;
            this.dtpLastClaimLineCreatedDate.Enabled = true;
            this.dtpLastClaimAdjCreatedDate.Enabled = true;
            this.txtEncounterSubmitterID.Enabled = true;
            this.txtCountyAddress.Enabled = true;
            this.txtCountyCity.Enabled = true;
            this.txtCountyState.Enabled = true;
            this.txtCountyZipCode.Enabled = true;
            this.txtCYAReportSentTo1.Enabled = true;
            this.txtCYAReportSentTo2.Enabled = true;
            this.txtCYAReportSentTo3.Enabled = true;
            this.txtVideoFolder.Enabled = true;
            this.txtMCONUMBER.Enabled = true;
            this.txtMCONAME.Enabled = true;
            this.txtOtherSubmitterIDISA.Enabled = true;
            this.txtOtherSubmitterIDNM.Enabled = true;
            this.txtHomelessZipCode.Enabled = true;
            this.txtReportAddressFooterText.Enabled = true;
            this.txtCrisisTestPID.Enabled = true;
            this.txtCrisisProdPID.Enabled = true;
            this.txtMPI_BCM.Enabled = true;
            this.txtNPI_BCM.Enabled = true;
        }

        private void btnDisableAll_Click(object sender, EventArgs e)
        {
            this.txtID.Enabled = false;
            this.txtMessagingRefresh.Enabled = false;
            this.txtAutoLogOutTime.Enabled = false;
            this.txtCrisisInterventionRefresh.Enabled = false;
            this.txtCountyMAIDNumber.Enabled = false;
            this.txtCountyCode.Enabled = false;
            this.txtCountyAlphaCode.Enabled = false;
            this.txtLocationCode.Enabled = false;
            this.txtCountyName.Enabled = false;
            this.txtMemberRegistrationRefresh.Enabled = false;
            this.txtPeopleSoftVoucherNumber.Enabled = false;
            this.txtBESNUMBERTEST.Enabled = false;
            this.txtBESNUMBERLIVE.Enabled = false;
            this.txtMPINUMBERTEST.Enabled = false;
            this.txtMPINUMBERLIVE.Enabled = false;
            this.txtCOUNTYMCOCODEN.Enabled = false;
            this.txtCOUNTYMCOCODEA.Enabled = false;
            this.txtDPWNAME.Enabled = false;
            this.txtCONTACTNAME.Enabled = false;
            this.txtCONTACTPHONE.Enabled = false;
            this.txtCONTACTFAX.Enabled = false;
            this.txtCONTACTEMAIL.Enabled = false;
            this.txtLASTCONTROLNUM.Enabled = false;
            this.txtSubSystemNumber.Enabled = false;
            this.txtPFVoucherNumber.Enabled = false;
            this.txtPlanProviderID.Enabled = false;
            this.txtMPI_ICM.Enabled = false;
            this.txtMPI_TSM.Enabled = false;
            this.txtMPI_CI.Enabled = false;
            this.txtMPI_EI.Enabled = false;
            this.txtMPI_RC.Enabled = false;
            this.txtNPI_ICM.Enabled = false;
            this.txtNPI_TSM.Enabled = false;
            this.txtNPI_CI.Enabled = false;
            this.txtNPI_RC.Enabled = false;
            this.txtNPI_EI.Enabled = false;
            this.txtscanneddocsfolder.Enabled = false;
            this.txtEIN.Enabled = false;
            this.txtQueryTimeout.Enabled = false;
            this.dtpLastClaimDtlCreatedDate.Enabled = false;
            this.dtpLastClaimLineCreatedDate.Enabled = false;
            this.dtpLastClaimAdjCreatedDate.Enabled = false;
            this.txtEncounterSubmitterID.Enabled = false;
            this.txtCountyAddress.Enabled = false;
            this.txtCountyCity.Enabled = false;
            this.txtCountyState.Enabled = false;
            this.txtCountyZipCode.Enabled = false;
            this.txtCYAReportSentTo1.Enabled = false;
            this.txtCYAReportSentTo2.Enabled = false;
            this.txtCYAReportSentTo3.Enabled = false;
            this.txtVideoFolder.Enabled = false;
            this.txtMCONUMBER.Enabled = false;
            this.txtMCONAME.Enabled = false;
            this.txtOtherSubmitterIDISA.Enabled = false;
            this.txtOtherSubmitterIDNM.Enabled = false;
            this.txtHomelessZipCode.Enabled = false;
            this.txtReportAddressFooterText.Enabled = false;
            this.txtCrisisTestPID.Enabled = false;
            this.txtCrisisProdPID.Enabled = false;
            this.txtMPI_BCM.Enabled = false;
            this.txtNPI_BCM.Enabled = false;
        }

        private void btnHideAll_Click(object sender, EventArgs e)
        {
            this.txtID.Visible = false;
            this.txtMessagingRefresh.Visible = false;
            this.txtAutoLogOutTime.Visible = false;
            this.txtCrisisInterventionRefresh.Visible = false;
            this.txtCountyMAIDNumber.Visible = false;
            this.txtCountyCode.Visible = false;
            this.txtCountyAlphaCode.Visible = false;
            this.txtLocationCode.Visible = false;
            this.txtCountyName.Visible = false;
            this.txtMemberRegistrationRefresh.Visible = false;
            this.txtPeopleSoftVoucherNumber.Visible = false;
            this.txtBESNUMBERTEST.Visible = false;
            this.txtBESNUMBERLIVE.Visible = false;
            this.txtMPINUMBERTEST.Visible = false;
            this.txtMPINUMBERLIVE.Visible = false;
            this.txtCOUNTYMCOCODEN.Visible = false;
            this.txtCOUNTYMCOCODEA.Visible = false;
            this.txtDPWNAME.Visible = false;
            this.txtCONTACTNAME.Visible = false;
            this.txtCONTACTPHONE.Visible = false;
            this.txtCONTACTFAX.Visible = false;
            this.txtCONTACTEMAIL.Visible = false;
            this.txtLASTCONTROLNUM.Visible = false;
            this.txtSubSystemNumber.Visible = false;
            this.txtPFVoucherNumber.Visible = false;
            this.txtPlanProviderID.Visible = false;
            this.txtMPI_ICM.Visible = false;
            this.txtMPI_TSM.Visible = false;
            this.txtMPI_CI.Visible = false;
            this.txtMPI_EI.Visible = false;
            this.txtMPI_RC.Visible = false;
            this.txtNPI_ICM.Visible = false;
            this.txtNPI_TSM.Visible = false;
            this.txtNPI_CI.Visible = false;
            this.txtNPI_RC.Visible = false;
            this.txtNPI_EI.Visible = false;
            this.txtscanneddocsfolder.Visible = false;
            this.txtEIN.Visible = false;
            this.txtQueryTimeout.Visible = false;
            this.dtpLastClaimDtlCreatedDate.Visible = false;
            this.dtpLastClaimLineCreatedDate.Visible = false;
            this.dtpLastClaimAdjCreatedDate.Visible = false;
            this.txtEncounterSubmitterID.Visible = false;
            this.txtCountyAddress.Visible = false;
            this.txtCountyCity.Visible = false;
            this.txtCountyState.Visible = false;
            this.txtCountyZipCode.Visible = false;
            this.txtCYAReportSentTo1.Visible = false;
            this.txtCYAReportSentTo2.Visible = false;
            this.txtCYAReportSentTo3.Visible = false;
            this.txtVideoFolder.Visible = false;
            this.txtMCONUMBER.Visible = false;
            this.txtMCONAME.Visible = false;
            this.txtOtherSubmitterIDISA.Visible = false;
            this.txtOtherSubmitterIDNM.Visible = false;
            this.txtHomelessZipCode.Visible = false;
            this.txtReportAddressFooterText.Visible = false;
            this.txtCrisisTestPID.Visible = false;
            this.txtCrisisProdPID.Visible = false;
            this.txtMPI_BCM.Visible = false;
            this.txtNPI_BCM.Visible = false;
        }

        private void btnShowAll_Click(object sender, EventArgs e)
        {
            this.txtID.Visible = true;
            this.txtMessagingRefresh.Visible = true;
            this.txtAutoLogOutTime.Visible = true;
            this.txtCrisisInterventionRefresh.Visible = true;
            this.txtCountyMAIDNumber.Visible = true;
            this.txtCountyCode.Visible = true;
            this.txtCountyAlphaCode.Visible = true;
            this.txtLocationCode.Visible = true;
            this.txtCountyName.Visible = true;
            this.txtMemberRegistrationRefresh.Visible = true;
            this.txtPeopleSoftVoucherNumber.Visible = true;
            this.txtBESNUMBERTEST.Visible = true;
            this.txtBESNUMBERLIVE.Visible = true;
            this.txtMPINUMBERTEST.Visible = true;
            this.txtMPINUMBERLIVE.Visible = true;
            this.txtCOUNTYMCOCODEN.Visible = true;
            this.txtCOUNTYMCOCODEA.Visible = true;
            this.txtDPWNAME.Visible = true;
            this.txtCONTACTNAME.Visible = true;
            this.txtCONTACTPHONE.Visible = true;
            this.txtCONTACTFAX.Visible = true;
            this.txtCONTACTEMAIL.Visible = true;
            this.txtLASTCONTROLNUM.Visible = true;
            this.txtSubSystemNumber.Visible = true;
            this.txtPFVoucherNumber.Visible = true;
            this.txtPlanProviderID.Visible = true;
            this.txtMPI_ICM.Visible = true;
            this.txtMPI_TSM.Visible = true;
            this.txtMPI_CI.Visible = true;
            this.txtMPI_EI.Visible = true;
            this.txtMPI_RC.Visible = true;
            this.txtNPI_ICM.Visible = true;
            this.txtNPI_TSM.Visible = true;
            this.txtNPI_CI.Visible = true;
            this.txtNPI_RC.Visible = true;
            this.txtNPI_EI.Visible = true;
            this.txtscanneddocsfolder.Visible = true;
            this.txtEIN.Visible = true;
            this.txtQueryTimeout.Visible = true;
            this.dtpLastClaimDtlCreatedDate.Visible = true;
            this.dtpLastClaimLineCreatedDate.Visible = true;
            this.dtpLastClaimAdjCreatedDate.Visible = true;
            this.txtEncounterSubmitterID.Visible = true;
            this.txtCountyAddress.Visible = true;
            this.txtCountyCity.Visible = true;
            this.txtCountyState.Visible = true;
            this.txtCountyZipCode.Visible = true;
            this.txtCYAReportSentTo1.Visible = true;
            this.txtCYAReportSentTo2.Visible = true;
            this.txtCYAReportSentTo3.Visible = true;
            this.txtVideoFolder.Visible = true;
            this.txtMCONUMBER.Visible = true;
            this.txtMCONAME.Visible = true;
            this.txtOtherSubmitterIDISA.Visible = true;
            this.txtOtherSubmitterIDNM.Visible = true;
            this.txtHomelessZipCode.Visible = true;
            this.txtReportAddressFooterText.Visible = true;
            this.txtCrisisTestPID.Visible = true;
            this.txtCrisisProdPID.Visible = true;
            this.txtMPI_BCM.Visible = true;
            this.txtNPI_BCM.Visible = true;
        }
    }
}
